graphite:
  ports:
  - 2003:2003/tcp
  image: hopsoft/graphite-statsd
  volumes:
  - /root/monitoring/data/graphite:/opt/graphite/storage
  stdin_open: true
  tty: true
grafana:
  ports:
  - 3000:3000/tcp
  image: grafana/grafana:latest
  links:
  - graphite:graphite
  volumes:
  - /root/monitoring/data/grafana:/var/lib/grafana
  environment:
    - GF_SECURITY_ADMIN_PASSWORD=password
  stdin_open: true
  tty: true
collectd-metrics:
  environment:
    - GRAPHITE_HOST=graphite
    - GRAPHITE_PORT=2003
    - HOST_NAME=testHost
  links:
    - graphite:graphite
  image: andreasjansson/collectd-write-graphite
