version: '2'
services:
  web:
    image: gitlab/gitlab-ce:8.15.2-ce.0
    restart: always
    hostname: gitlab.example.com
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
    expose:
     - 80
    ports:
      - 8080:80
      - 443:443
      - 22:22
    volumes:
      - ./storage/config:/etc/gitlab
      - ./storage/logs:/var/log/gitlab
      - ./storage/data:/var/opt/gitlab
    network_mode: "bridge"
  runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    links:
      - web:gitlab.example.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.toml:/etc/gitlab-runner/config.toml
    network_mode: "bridge"