version: '2'
services:
  mongo:
    image: mongo:3
    command: "mongod --smallfiles"
    volumes:
      - ./data/mongo:/data/db
  elasticsearch:
    image: elasticsearch:2
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
  graylog:
    image: graylog2/server:2.1.2-1
    volumes:
      - ./data/graylog/data/journal:/usr/share/graylog/data/journal
      - ./data/graylog/plugin:/usr/share/graylog/plugin
    environment:
      GRAYLOG_PASSWORD_SECRET: randomsecret
      GRAYLOG_ROOT_PASSWORD_SHA2: passwordhash
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
      GRAYLOG_ROOT_TIMEZONE: Europe/Moscow
    links:
      - mongo:mongo
      - elasticsearch:elasticsearch
    ports:
      - "9000:9000"
      - "5044:5044"
      - "12201/udp:12201/udp"
      - "1514/udp:1514/udp"
