version: '2'
services:
  filebeat:
    image: prima/filebeat:latest
    stdin_open: true
    volumes:
    - /var/filebeat/filebeat.yml:/filebeat.yml
    - /var/www/yii-site:/var/www/yii-site
    tty: true
    labels:
      io.rancher.container.pull_image: always

