filebeat.prospectors:
- input_type: log
  multiline:
    pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2} '
    negate: true
    match: after
  paths:
    - /var/www/yii-site/*/runtime/logs/*.log
output.logstash:
  enabled: true
  hosts: ["localhost:5044"]